# builder

FROM node:alpine as builder

RUN apk add --no-cache tini

WORKDIR /app/client

COPY ./client/package.json .
RUN yarn -s
COPY ./client .
RUN yarn build

# server

FROM node as server

RUN apt-get update -y -q && apt-get install -y -q gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

WORKDIR /app/server

COPY ./server/package.json .
RUN yarn -s
COPY ./server .
COPY --from=builder /app/client/build /app/server/public

ENTRYPOINT ["/tini", "--"]
