version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["yarn", "start:dev"]
    volumes:
      - "./server/src:/app/server/src"
      - "./server/typecheck.log:/app/server/typecheck.log"
      - "./client/build:/app/server/public"
      - "./client/src/validators:/app/server/src/validators"
      - "./client/src/actions/battle:/app/server/src/actions/battle"
      - "./client/src/actions/user.ts:/app/server/src/actions/user.ts"
      - "./client/src/actions/middlewares:/app/server/src/actions/middlewares"
      - "./client/src/selectors/battle:/app/server/src/selectors/battle"
      - "./client/src/lib:/app/server/src/lib"
      - "./client/src/utils/common.ts:/app/server/src/utils/common.ts"
      - "./client/src/constants.ts:/app/server/src/constants.ts"
    env_file: ./server/env
    restart: on-failure
    ports:
      - "3030:3000"
    links:
      - mongodb
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    volumes:
      - "./data:/data"

