version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["yarn", "start:dev"]
    volumes:
      - "./server/src:/app/server/src"
      - "./client/build:/app/client/public"
      - "./core/:/app/server/node_modules/core"
    env_file: ./server/env
    restart: on-failure
    ports:
      - "3030:3000"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - "./data:/data"

