version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["yarn", "start:dev"]
    volumes:
      - "./server/src:/app/server/src"
      - "./client/build:/app/server/public"
    env_file: ./server/env
    restart: on-failure
    ports:
      - "3030:3000"
    links:
      - mongodb
    depends_on:
      - mongodb


# testing:
#   build:
#     context: .
#     dockerfile: Dockerfile.test.dev
#   command: ["yarn", "start:dev"]
#   volumes:
#     - "./test-data:/data"
#     - "./server/src:/app/server/src"
#     - "./server/test:/app/server/test"
#     - "./client/build:/app/server/public"
#   env_file: ./server/env.test
#   restart: on-failure
#   links:
#     - mongodb
#   depends_on:
#     - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - "./data:/data"

