FROM alekzonder/puppeteer:latest

ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

WORKDIR /app/server

COPY ./server/package.json .
RUN yarn -s
COPY ./server .

ENTRYPOINT ["/tini", "--"]
