# builder

FROM node:alpine as builder

RUN apk add --no-cache tini

WORKDIR /app/client

COPY ./client/package.json .
RUN yarn -s
COPY ./client .
RUN yarn build

# server

FROM alekzonder/puppeteer:latest as server

ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

WORKDIR /app/server

COPY ./server/package.json .
RUN yarn -s
COPY ./server .
COPY --from=builder /app/client/build /app/server/public

ENTRYPOINT ["/tini", "--"]
