# server

FROM node:alpine as server

RUN apk add --no-cache tini

WORKDIR /app/server

COPY ./core /app/core
COPY ./server/package.json .
RUN yarn -s
COPY ./server .

ENTRYPOINT ["/sbin/tini", "--"]
