version: "3"

services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["yarn", "start"]
    env_file: ./server/env.test
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - "./data:/data"
