version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start"]
    env_file: ./server/env
    restart: on-failure
    ports:
      - "3030:3000"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - "./data:/data"

