//!
//! You need put `generated by effect action` which lead to "user interaction"
//! STRICTLY at the and of `allEffects` and such action should be THE ONLY ONE.
//!

import { unitAvailable } from "../../actions/battle/unit";
import { PLAYER_ADD_UNIT } from "../../actions/battle/player";

//
//                  action     [ ]
//                    |
//                  \ v /       v
//                   |e|
//                   |f|      [a,a] :post
//                   |f|
//                   |e|        v
//                   |c|
//                   |t|      [a,a,a] :post
//                   |s|
//                    |         v
//                    v
// [                action, ...postactions]
//

export function applyEffects(effects, action) {
  return effects.reduce((allActions, eff) => applyEffect(eff, allActions), [
    action
  ]);
}

const MAKE_UNIT_AVAILABLE = "MAKE_UNIT_AVAILABLE";

//
// ============ reducer ============
//

export function applyEffect(effect, allActions) {
  switch (effect.type) {
    case MAKE_UNIT_AVAILABLE:
      return makeUnitAvailable(effect, allActions);
  }
}

function makeUnitAvailable(effect, allActions) {
  let [action, ...postActions] = allActions;
  const { type, payload } = action;

  if (action.type !== PLAYER_ADD_UNIT) {
    postActions.push(unitAvailable(payload.unit));
  }

  return [action, ...postActions];
}

//
// ============ Effects ============
//

export function makeUnitAvailableEffect() {
  return {
    type: MAKE_UNIT_AVAILABLE
  };
}
